<?php

return [
    'image/*',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.openxmlformats-officedocument.presentationml.template',
    'application/vnd.ms-excel',
    'application/vnd.ms-access',
    'text/plain',
    'text/csv',
    'text/html',
    'application/xml',
    'application/json',
    'application/vnd.ms-powerpoint',
    'application/x-rar-compressed',
    'application/zip',
    'application/x-tar',
    'audio/mpeg',
    'video/mp4',
];
